In [5]:
import numpy as np
numpy_array = np.array([1,2,3,4])
print(numpy_array)
print(type(numpy_array))
print(np.arange(10))

[1 2 3 4]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [24]:
lst = list(range(1000))
%timeit [ i**2 for i in lst]
# print([ i**2 for i in lst])

213 µs ± 5.44 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
a = np.arange(1000)
%timeit a**2
# print(a**2)

1.61 µs ± 73.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [96]:
a = np.array([1,2,3,4]) #1-D (vector)
print(a)
print(a.shape) #shape - no of elements
print(len(a)) # length of an 1-D array
print(a.ndim) # ndim = no of dimensons

print('\n')
a = np.array([[1,2,3,4],[5,6,7,8]]) #2-D (matrix)
print(a)
print(a.shape) #shape - (rows, columns)
print(len(a))  #returns the size of the first dimension (rows)
print(a.ndim) # ndim = no of dimensons

print('\n')
a = np.array([[[1,2,3,4],[5,6,7,8]], [[9,10,11,12], [13,14,15,16]], [[17,18,19,20],[21,22,23,24]]]) 
#3-D (tensor), n-D (Tensor) where n>2
print(a)
print(a.shape) #shape - (no of matrices, rows of each matrix,columns of each matrix)
# (3,2,4) means there are 3 matrices of size 2*4 (2 rows ans 4 columns)
print(len(a))  #returns the size of the first dimension (no of matrices)
print(a.ndim) # ndim = no of dimensons

[1 2 3 4]
(4,)
4
1


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
2


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
(3, 2, 4)
3
3


In [67]:
'''Different ways of creating numpy arrays'''
import numpy as np
a = np.arange(10)
print(a)
a = np.arange(1,10) #(start, end, step-size)
print(a)
a = np.arange(0,10,2) #(start, end, step-size)
print(a)

print('\n')
a = np.linspace(0,1,6) #start, end, number of points i.e, dividing space between 0 and 1 into '6' equal spaced regions
print(a)
a = np.linspace(1,10,10) #start, end, number of points i.e, dividing space between 1 and 10 into '10' equal spaced regions
print(a)
print(a)
a = np.linspace(0,10,10) #start, end, number of points i.e, dividing space between 0 and 10 into '10' equal spaced regions
print(a)

print('\n')
a = np.ones((3,3))
print(a)

print('\n')
a = np.zeros((3,3))
print(a)

print('\n')
a = np.eye(4,4) #identity matrix
print(a)

print('\n')
a = np.diag([1,2,3,4]) # creates a diagonal matrix with 4*4 shape and diagonal elements as (1,2,3,4)
print(a)
print(np.diag(a))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


[0.  0.2 0.4 0.6 0.8 1. ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 2 3 4]


In [75]:
a = np.arange(10)
print(a)
print(a[1:8:2]) # [startindex: endindex(exclusive) : step]

print('\n')
a = np.arange(10) #we can also combine assignment and slicing:
a[5:] = 10
print(a)

print('\n')
b = np.arange(5)
a[5:] = b[::-1]  #assigning b[::-1] = b[0:len:-1]; -1 means process in reverse-order
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


[ 0  1  2  3  4 10 10 10 10 10]


[0 1 2 3 4 4 3 2 1 0]


In [89]:
'''Copies and Views'''
a = np.arange(10)
print(a)
b = a[::2] #shallow copy
print(b)
print(np.shares_memory(a,b)) 
b[2] = 100
print(a)
print(b)

print('\n')
a = np.arange(10)
print(a)
c = a[::2].copy() #deep copy
print(c)
print(np.shares_memory(a,c))
c[2] = 100
print(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True
[  0   1   2   3 100   5   6   7   8   9]
[  0   2 100   6   8]


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
False
[0 1 2 3 4 5 6 7 8 9]
[  0   2 100   6   8]


In [93]:
'''Fancy indexing in numpy'''
a = np.random.randint(0, 20, 15)
print(a)

mask = (a % 2 == 0)
b = a[mask] # masking creates copies not views i.e, deep-copy
print(b)
b[1] = 1111
print(a)
print(b)

print('\n')
print(a)
a[mask] = -9
print(a)

print('\n')
a = np.arange(0, 100, 10) #Indexing with an array of integers
print(a)
print(a[[1,5,6,1]])

[12 14 16 16 16 14  3 15 12  7 13  6  1 13 17]
[12 14 16 16 16 14 12  6]
[12 14 16 16 16 14  3 15 12  7 13  6  1 13 17]
[  12 1111   16   16   16   14   12    6]


[12 14 16 16 16 14  3 15 12  7 13  6  1 13 17]
[-9 -9 -9 -9 -9 -9  3 15 -9  7 13 -9  1 13 17]


[ 0 10 20 30 40 50 60 70 80 90]
[10 50 60 10]


In [101]:
'''Elementwise Operations'''
a = np.arange(10)
print(a + 20)
print(a**2)
b = np.ones(10) + 1
print( a - b)

print('\n')
m = np.diag([1,2,3,4])
print(m)
print(m*m) #matrix multiplication
print(m.dot(m)) #matrix multiplication

[20 21 22 23 24 25 26 27 28 29]
[ 0  1  4  9 16 25 36 49 64 81]
[-2. -1.  0.  1.  2.  3.  4.  5.  6.  7.]


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [124]:
'''Comparisons'''
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
print(a==b)
print(a>=b)
c = np.array([1, 2, 3, 4])
print(np.array_equal(a,c)) # np.array_equal() checks both arrays are equal are not
print(np.array_equal(a,b)) # np.array_equal() checks both arrays are equal are not

print('\nLogical Operations')
a = np.array([1,0,1,1], dtype=bool)
b = np.array([0,0,1,1], dtype=bool)
print(np.logical_or(a,b))
print(np.logical_and(a,b))

print('\nTranscendental functions')
a = np.arange(1,10,2)
print(a)
print(np.sin(a))
print(np.log(a))
print(np.mean(a))
print(np.median(a))
print('***********************************************')
print(np.max(a))
print(np.argmax(a))
print(np.min(a))
print(np.argmin(a))
print('***********************************************')
print(np.exp(a))
print(np.sum(a))

[False  True False  True]
[False  True  True  True]
True
False

Logical Operations
[ True False  True  True]
[False False  True  True]

Transcendental functions
[1 3 5 7 9]
[ 0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849]
[0.         1.09861229 1.60943791 1.94591015 2.19722458]
5.0
5.0
***********************************************
9
4
1
0
***********************************************
[2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 8.10308393e+03]
25


In [135]:
'''Operations on Matrices'''
a = np.array([[1, 2, 3], [5, 6, 1]])
print(a)
print('*******************************************')
print(np.mean(a, axis = 1)) #axis=1 : row
print(np.mean(a, axis = 0)) #axis=0 : column
print(a.mean())
print(np.mean(a))
print('*******************************************')
print(np.median(a, axis = 1)) #axis=1 : row
print(np.median(a, axis = 0)) #axis=0 : column
print(np.median(a))
print('*******************************************')
print(np.std(a, axis = 1)) #axis=1 : row
print(np.std(a, axis = 0)) #axis=0 : column
print(a.std())
print(np.std(a))

[[1 2 3]
 [5 6 1]]
*******************************************
[2. 4.]
[3. 4. 2.]
3.0
3.0
*******************************************
[2. 5.]
[3. 4. 2.]
2.5
*******************************************
[0.81649658 2.1602469 ]
[2. 2. 1.]
1.9148542155126762
1.9148542155126762


In [152]:
'''Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years'''
#load data into numpy array object
data = np.loadtxt('populations.txt')
print(data) # year	hare	lynx	carrot
print(type(data))

print('\n')
year, hares, lynxes, carrots = data.T #columns to variables
print(year)

print('\nThe mean population over time')
hares_lynxes_carrots_matrix = data[ : , 1:]
print(hares_lynxes_carrots_matrix)
print(hares_lynxes_carrots_matrix.mean()) #mean

print('\nSample standard deviations')
print(np.std(hares_lynxes_carrots_matrix, axis = 0))

print('\nWhich species has the highest population each year?')
print(np.argmax(hares_lynxes_carrots_matrix, axis = 1))

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]
<class 'numpy.ndarray'>


[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]

The mean population over time
[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38

In [171]:
'''BroadCasting'''
a = np.tile(np.array([10,20,40]), (3,1))
print(a)
print('****************************')
b = np.array([0, 1, 2])
print(b)
print('****************************')
print(a + b)

print('\n')
a = np.arange(0, 40, 10)
print(a)
print(a.shape)
print('****************************')
a = a[ : , np.newaxis] # convertinf into 2-D array
print(a)
print(a.shape)
print('****************************')
print(a)
print(b)
print('****************************')
print(a+b)

[[10 20 40]
 [10 20 40]
 [10 20 40]]
****************************
[0 1 2]
****************************
[[10 21 42]
 [10 21 42]
 [10 21 42]]


[ 0 10 20 30]
(4,)
****************************
[[ 0]
 [10]
 [20]
 [30]]
(4, 1)
****************************
[[ 0]
 [10]
 [20]
 [30]]
[0 1 2]
****************************
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [191]:
'''Array Shape Manipulation'''
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape)
print('**************************')
print(a.ravel()) #Return a contiguous flattened array. 
#A 1-D array, containing the elements of the input, is returned. A copy is made only if needed
print('**************************')
print(a.T.ravel())
print('**************************')
b = a.ravel()
b = b.reshape((3, 2)) #reshape of an array
print(b)

[[1 2 3]
 [4 5 6]]
(2, 3)
**************************
[1 2 3 4 5 6]
**************************
[1 4 2 5 3 6]
**************************
[[1 2]
 [3 4]
 [5 6]]


In [196]:
print('\n')
a = np.arange(4*3*2).reshape(4, 3, 2)
print(a)
print('**************************')
a = np.array([[5, 4, 6], [2, 3, 2]])
print(a)
b = np.sort(a, axis=1)
print('**************************')
print(b)



[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
**************************
[[5 4 6]
 [2 3 2]]
**************************
[[4 5 6]
 [2 2 3]]


In [195]:
#sorting with fancy indexing
a = np.array([40, 30, 10, 20])
j = np.argsort(a)
print(j)
print(a[j])

[2 3 1 0]
[10 20 30 40]
